version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: US/Eastern
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: semantic-release
    versions:
    - "< 15.12.3, >= 15.12.2.a"
  - dependency-name: semantic-release
    versions:
    - "< 15.12.4, >= 15.12.3.a"
  - dependency-name: semantic-release
    versions:
    - "< 15.12.6, >= 15.12.5.a"
  - dependency-name: semantic-release
    versions:
    - "< 15.13.2, >= 15.13.1.a"
  - dependency-name: semantic-release
    versions:
    - "< 15.13.3, >= 15.13.2.a"
  - dependency-name: semantic-release
    versions:
    - "< 15.13.4, >= 15.13.3.a"
  - dependency-name: semantic-release
    versions:
    - ">= 15.13.4.a, < 15.13.5"
  - dependency-name: semantic-release
    versions:
    - ">= 15.13.7.a, < 15.13.8"
  - dependency-name: semantic-release
    versions:
    - ">= 15.13.8.a, < 15.13.9"
  - dependency-name: semantic-release
    versions:
    - "< 15.9.10, >= 15.9.9.a"
  - dependency-name: semantic-release
    versions:
    - "< 15.9.11, >= 15.9.10.a"
  - dependency-name: semantic-release
    versions:
    - "< 15.9.12, >= 15.9.11.a"
  - dependency-name: semantic-release
    versions:
    - "< 15.9.13, >= 15.9.12.a"
  - dependency-name: semantic-release
    versions:
    - "< 15.9.15, >= 15.9.14.a"
  - dependency-name: semantic-release
    versions:
    - "< 15.9.4, >= 15.9.3.a"
  - dependency-name: semantic-release
    versions:
    - "< 15.9.5, >= 15.9.4.a"
  - dependency-name: semantic-release
    versions:
    - "< 15.9.6, >= 15.9.5.a"
  - dependency-name: semantic-release
    versions:
    - "< 15.9.9, >= 15.9.8.a"
  - dependency-name: "@semantic-release/git"
    versions:
    - "< 7.0.4, >= 7.0.3.a"
  - dependency-name: "@types/node"
    versions:
    - 14.14.23
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.27
    - 14.14.28
    - 14.14.29
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.0
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: typescript
    versions:
    - 4.2.3
  - dependency-name: puppeteer
    versions:
    - 7.0.0
    - 7.0.1
    - 7.0.3
    - 7.0.4
    - 7.1.0
    - 8.0.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.0
    - 4.16.1
    - 4.17.0
    - 4.18.0
  - dependency-name: semantic-release
    versions:
    - 17.3.8
    - 17.3.9
    - 17.4.0
    - 17.4.1
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
  - dependency-name: eslint
    versions:
    - 7.18.0
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: US/Eastern
  open-pull-requests-limit: 10
