language: rust
rust: stable

cache:
  cargo: true
  directories:
    - $HOME/.cache/yarn
    - $HOME/.npm
    - node_modules
    - $TRAVIS_BUILD_DIR/node_modules
    - $TRAVIS_BUILD_DIR/.cache

env:
  global:
    - secure: nZDrtbcwUqKYo90pOG59EJ/etCbqbjMfMTaEPsjSfFWd/zuTY1WASkgjh0EjoL9g/c28Xh02yeNfcRP2QD+O2ArztRrDhx/D/zP+w0z5tu6oF9NX2rlfM3Nogb1EM7S5wwnpeS3vm7L7NQY77UqLTKZJSojZUooLPbTUTfDgFW2NLhbTKRt34FCcctAW2tvYXID9ovNT/lOdLJmT5WXS+nW/lbZcsICO66a1uK16bH3D7A58XFfLtHCbaxlD4Y+P30V81EDpaHLDqYFyQ5FAacTs/rEWJQES/EoqCPacL5HKuwwA2R0QGskohdMnQSVu6J5ic4HbreXYrZq1Nb901yOfiNiovY/eUDgh0SCzmFxMV2GBTrXcepeqHf4YIotCJpO7DLqA0w9xjQD16Id0ugaSJQOnp8oo2Wa2XTn6H2r0z3mdkSNdVmQWbxcgnMH5dwfUr9w0JypqgzYGKVKJNofrAgckh2dFDfgOD4imv5IuKYqJSqUOr20nEq+vr/1/iy388oZKI5KujnDMc+d0H7NcX2QvwxaTF8bFHiThhEeV12nMQgPMwU2xCNyWNyg8TacaeRrDgrK1n3bgQjVh3erWryaac2j+Ut0DUPC7v2RX4qPV7LzWrAaGjknDIVAND28zhyfP/8x7L8DXOzhak/lIqtjVaBnI12Maj2HW0ik=
    - secure: dtAAf384A7LEyBlzxvtasz92TJWbgWnxjwH+fyE2fzQArwyZ5XpyZmF0C9ih0npNtApmYKAhCQ1R4Wi2Qf1azK7Gl33NNIpAwGSQjPRw4TQpv3LliYe/TEgGKo2ngA0XpzCyc0Fw8Yqbj5dTbzYiCJepymqIZ4CRrmF//Ke/uahjDEu25Qo9q3AlDeymdu02RwRXZGs2DBK+ktwiVot1khNRBQxpkcI2VETpTi+L1DV2rs2Z9xobe+mYO4K1ld9JTycih90eHYPMm2DFQ08ZapeZB05Y6kbHD5WPVQOvB5syEUYVUQeFk3GzLT7bpAFiWm2MM4qg69tDZg09plwUoVD2GMqbglPsfJR5XLQMEoqUVwYNOOKRDzHdotgBtM93PmjxE8cXKC2iq3bcKyVxrZclXcFdzWhLI/EErEZG8vtOHgaYjmbFUy97yX88j7XVih3MQdxM+74K6Rbca5n6GanzVK3Oq2xdWKAAFnSs0CGrEiWXKGa070MR8ktOnc1PdNJ24pAZVNXsFn4tm+Siph6cPcUMH6QJE7S0P12bb/YgdRq5wbsvk6qL/4X2x+V/xDVJO7uMGzemIIWAkNA/GYbRIcgX9yPLNMvcDa5YI5v2XjsxKFo4MOA94Ql03cSCP6K7FgxNCKAtmlRSePfP31wbZIX2xGog8nsubRG0AqM=
    - secure: TzFxRXCc9oqlXn9eHmdP21WX4FrN77/H96V6iAXn7w+8ug2rklpYgzsIk/4bLZHUtu0G/FsQ3Ar3jhBToM4VrqNdjZBgYJYvsBTctP6R7W/vyI/ib3Erfuj06PxRjJdEdG7epVwkz/YQv2Spx66CDNq6ufLbMNsmq5v1VJIBU1w5w6yjIC0onOHFOeRvFAfypD9Axxq1YZtp35PXM4iIuOqVSiyCKZhaos+WYGP8C24sMr1Y9olD/6VXwVKCgoD0dorGnS7s+egM1HLDu2fx5ClOsKPhh91IzYSNNCCMrF+Fbtq3cgzmzPsHyOOxLIAW78alm5OXRXWH/3tp3laLxqrqXKr7GDDMI6fpflKdk9pz55MSQVIrHhqQcXAJtNR4m1CzszYDiLf9wb20taSyo3TCK3D2vTWi3Ym8UmtCdn/oGnZ4g73cYEp6YbBrph1MTs0ulNc5t54/1e9KUbUjWxEuzDtBHtYsYg3CQ1rDmVn6GxpvBNCJcpGGg5JUlgtMdvtENAmiba0WwwOytY54TAJs7kSeT34fI3XOVaoXJsLyqjDeOlQO1uXEzQ2lqXgKDIRDInyJA+joN5mFDQPD9YJ8vOKot3by2m3931Ao2tmQ8jRWgPXPCiIhCH74FP1hm5GSq+A4o17YP2SW7ZWW1W8r8oM1rvvC+s85Z6mKZWA=

before_install:
  - nvm install

  # get the right npm version
  - NPM_VERSION=`node -pe "require('./package.json').engines.npm"`
  - if [ `npm --version` != "$NPM_VERSION" ]; then
    npm install --global npm@${NPM_VERSION};
    fi

  # get the right yarn version
  - YARN_VERSION=`node -pe "require('./package.json').engines.yarn"`
  - if [ `yarn --version` != "$YARN_VERSION" ]; then
    curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION;
    export PATH=$HOME/.yarn/bin:$PATH;
    fi

  - yarn install

before_script:
  - rustup target add wasm32-unknown-unknown
  - rustup component add rustfmt
  - (test -x $HOME/.cargo/bin/wasm-pack || cargo install wasm-pack)
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - cargo install-update -a

  # code climate's coverage reporter
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
    > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - './cc-test-reporter before-build'

script:
  - yarn lint
  - yarn test
  # for some reason the first build fails, @see: https://github.com/parcel-bundler/parcel/issues/1158#issuecomment-470664442
  - yarn build || yarn build

after_success:
  - test $TRAVIS_PULL_REQUEST != "false" && npx semantic-release-github-pr

deploy:
  # deploy a git tag, release notes, bump package.json, update READMEs
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
    on:
      branch: master

  # deploy the site
  - provider: pages
    repo: fartts/fartts.github.io
    target_branch: master
    github_token: '$GH_TOKEN'
    allow_empty_commit: true
    skip_cleanup: true
    keep_history: true
    local_dir: dist/
    on:
      branch: master

after_script:
  # report coverage
  - './cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT'
