language: node_js
node_js:
  - 'lts/*'
before_install:
  - YARN_VERSION=`node -pe "require('./package.json').engines.yarn"`
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
script:
  - yarn lint
  - yarn test
before_deploy:
  - yarn build
env:
  global:
    secure: iBe17f2iPiRkFgEOkAjQxlnx0tQvSn1c81nu2+6xLYy7+d4y6yaX4qZrORGZ25ItJfgLZ8B/RD4p9lZXP3WJYPxnrbJz2tmmBOqZENOAFWQfR9W1wYQdn0taZFvUmQ8t+HoabZH20SmzXzp04dBqsV9T2+nTf5i7+vqkc20Z8YOhRTqetFtwo8t+ioXNkXuXXdb52zFG9gUVsIFO4BHoPjUNccNDpKDsN5VcgFCZv+GVXho80F6BYkrIrx1fftNZ+vAHQhGSj7lGA5SLLGBvmCwJrcmMt0TPNkUnyyWgp3x/0xZFTc5KQENQSqLmhEGik9WRSFJyp2UgALA6CItD+117PCDN01jGwqlU1wVSqBK3AOFTLxiTfQte7LfZ7oK8/20m+/74du/F93s5F0k+hkPf36AyI8UG/h8p3+YWoDDWSJ6vOkPMTkMvvSqSsn+fgJa7tDEjD7QbSSlb2pVAib9WmsFieIQ6br5xJRP+lBILO8Yjq7N83/za8+J+UqNLPZrXCSKJiiE/ydqecotC5uYjrzc05ek9pUUc8I+rvnzocUrzSYGUlT9SQuknIK6CV9hFickrOl8C0fPWrdDdz6zR8F43/JqBT3VLpZ9dynP1b+IIkO+Mwx8J3p9pd+CCTMAPoGXOmZgmkFjZBku4INlrfhOh7GxVCGYCJfYetPU=
deploy:
  provider: pages
  repo: fartts/fartts.github.io
  target-branch: master
  on:
    branch: master
  github_token: $GITHUB_TOKEN
  allow_empty_commit: true
  keep_history: true
  skip_cleanup: true
  local_dir: dist/
