[package]
name = "pxs"
version = "0.1.0"
authors = ["Matt Hayes <matt@mysterycommand.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.38"

[dependencies.web-sys]
version = "0.3.15"
features = [
  'CanvasRenderingContext2d',
]
